# App\Entity\Product:
#   properties:
#     name:
#       - NotBlank: { message: "Le nom de prodyit est obligatore" }
#       - Length:
#           {
#             min: 3,
#             max: 255,
#             minMessage: "Le nom du produit doit faire plus de 3 caractéres",
#           }
#     price:
#       - NotBlank: { message: Le prix est obligatore' }
